import JSZip from 'jszip'
import { saveAs } from 'file-saver'

export async function exportToZip(files, projectName = 'my-website') {
  const zip = new JSZip()
  const root = zip.folder(projectName)

  // Add all generated files
  Object.entries(files).forEach(([filepath, content]) => {
    const parts = filepath.split('/')
    if (parts.length === 1) {
      root.file(filepath, content)
    } else {
      let folder = root
      for (let i = 0; i < parts.length - 1; i++) {
        folder = folder.folder(parts[i])
      }
      folder.file(parts[parts.length - 1], content)
    }
  })

  // Add setup scripts
  root.file('setup.sh', generateSetupScript(files))
  root.file('setup.bat', generateSetupBat(files))

  // Add .gitignore if not present
  if (!files['.gitignore']) {
    root.file('.gitignore', generateGitignore())
  }

  // Add .env.example if not present
  if (!files['.env.example'] && !files['.env']) {
    root.file('.env.example', generateEnvExample(files))
  }

  // Generate and add README if not present
  if (!files['README.md']) {
    root.file('README.md', generateReadme(projectName, files))
  }

  const blob = await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 }
  })

  saveAs(blob, `${projectName.replace(/\s+/g, '-').toLowerCase()}.zip`)
}

export async function exportSingleFile(filename, content) {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  saveAs(blob, filename)
}

export async function exportAsHTML(files, projectName = 'website') {
  // Find main HTML or build from React
  const htmlFile = Object.entries(files).find(([k]) =>
    k.endsWith('.html') || k.includes('index.html')
  )

  if (htmlFile) {
    const blob = new Blob([htmlFile[1]], { type: 'text/html;charset=utf-8' })
    saveAs(blob, `${projectName}.html`)
  }
}

function generateSetupScript(files) {
  const hasFrontend = Object.keys(files).some(f =>
    f.includes('frontend/') || f.includes('src/') || f === 'vite.config.js'
  )
  const hasBackend = Object.keys(files).some(f =>
    f.includes('backend/') || f.includes('server/') || f === 'server.js'
  )

  let script = `#!/bin/bash
echo "🚀 Setting up your website..."

`

  if (hasFrontend && hasBackend) {
    script += `# Install root dependencies
npm install

# Install frontend dependencies
if [ -d "frontend" ]; then
  cd frontend && npm install && cd ..
fi

# Install backend dependencies
if [ -d "backend" ]; then
  cd backend && npm install && cd ..
fi

# Copy env file
if [ -f ".env.example" ] && [ ! -f ".env" ]; then
  cp .env.example .env
  echo "⚠️  Please edit .env file with your settings"
fi

echo "✅ Setup complete!"
echo "🎯 Run: npm run dev"
`
  } else {
    script += `# Install dependencies
npm install

# Copy env file
if [ -f ".env.example" ] && [ ! -f ".env" ]; then
  cp .env.example .env
fi

echo "✅ Done! Run: npm run dev"
`
  }

  return script
}

function generateSetupBat(files) {
  return `@echo off
echo Setting up your website...
npm install
if exist .env.example (
  if not exist .env (
    copy .env.example .env
    echo Please edit .env file with your settings
  )
)
echo Setup complete! Run: npm run dev
pause
`
}

function generateGitignore() {
  return `# Dependencies
node_modules/
.pnp
.pnp.js

# Build outputs
dist/
build/
.next/
out/

# Environment files
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Logs
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*

# Editor
.vscode/
.idea/
*.swp
*.swo
.DS_Store

# Cache
.cache/
.parcel-cache/
.eslintcache

# Coverage
coverage/
*.lcov

# Misc
*.pem
.vercel
.netlify
`
}

function generateEnvExample(files) {
  const hasDB = Object.keys(files).some(f => f.includes('model') || f.endsWith('.sql'))
  const hasAuth = Object.keys(files).some(f =>
    f.includes('auth') || f.includes('jwt') || f.includes('middleware')
  )

  let env = `# App
PORT=3001
NODE_ENV=development
VITE_API_URL=http://localhost:3001

# Gemini AI
GEMINI_API_KEY=your_gemini_api_key_here

`

  if (hasDB) {
    env += `# Database
DATABASE_URL=mongodb://localhost:27017/myapp
# or for PostgreSQL:
# DATABASE_URL=postgresql://user:password@localhost:5432/myapp

`
  }

  if (hasAuth) {
    env += `# Auth
JWT_SECRET=your_super_secret_jwt_key_here
JWT_EXPIRES_IN=7d

`
  }

  env += `# Optional
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=your@email.com
SMTP_PASS=your_email_password
`

  return env
}

function generateReadme(projectName, files) {
  const hasBackend = Object.keys(files).some(f =>
    f.includes('server') || f.includes('backend')
  )
  const hasDB = Object.keys(files).some(f =>
    f.includes('model') || f.endsWith('.sql')
  )

  return `# ${projectName}

> Generated by **WebCraft AI Pro** — Full Stack Website Generator

## 🚀 Quick Start

\`\`\`bash
# 1. Install dependencies
npm install

# 2. Setup environment
cp .env.example .env
# Edit .env with your settings

# 3. Start development
npm run dev
\`\`\`

Open [http://localhost:5173](http://localhost:5173) in your browser.

## 📁 Project Structure

\`\`\`
${projectName}/
├── frontend/          # React + Vite frontend
│   ├── src/
│   │   ├── components/   # UI components
│   │   ├── pages/        # Page components
│   │   ├── hooks/        # Custom hooks
│   │   └── utils/        # Utilities
│   └── package.json
${hasBackend ? `├── backend/           # Node.js + Express API
│   ├── routes/       # API routes
│   ├── models/       # Data models
│   ├── middleware/   # Auth, validation
│   └── server.js` : ''}
${hasDB ? `├── database/          # Database schemas & seeds` : ''}
├── .env.example       # Environment variables template
└── README.md
\`\`\`

## 🛠️ Tech Stack

- **Frontend:** React 18, Vite, Three.js, Framer Motion
- **Styling:** CSS Modules / Tailwind CSS
- **3D:** Three.js, React Three Fiber
- **Animations:** Framer Motion, GSAP
${hasBackend ? `- **Backend:** Node.js, Express.js
- **API:** RESTful API` : ''}
${hasDB ? `- **Database:** MongoDB / PostgreSQL` : ''}

## 📜 Available Scripts

\`\`\`bash
npm run dev        # Start development server
npm run build      # Build for production
npm run preview    # Preview production build
${hasBackend ? 'npm run server     # Start backend only' : ''}
\`\`\`

## 🌐 Deployment

### Vercel (Recommended)
\`\`\`bash
npm i -g vercel
vercel
\`\`\`

### Netlify
\`\`\`bash
npm run build
# Upload dist/ folder to Netlify
\`\`\`

---

*Built with ❤️ by WebCraft AI Pro*
`
}
